### ISSUE TITLE
please remember to increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [kaiwolfram/Nozzle#3]
My updater just complained that v0.4.1-alpha has the same `versionCode` as the previous release. This makes updates more complex, especially users do not get update notifications. So just a friendly pointer here to please remember always to increase `versionCode` when preparing a release :wink:

**Comment by kaiwolfram** [comment]
Thank you for reminding me. I'll add it to my notes so I won't forget it again.
